### ISSUE TITLE
[Meta] Room reset

### ISSUE THREAD

**Issue by MorMundHS-MA** [informatik-mannheim/HSMA-CTT#125]
This feature requires the following sub-features:
- [x] A privileged check-in page with a room reset button #122
- [x] Prinout functionality for the new QR codes #124
- [x] Implement room reset in the backend #112 and tests for it #110

**Comment by Wifi-cable** [comment]
Text "Reset nur für Veranstaltungsleitende"  ist Korrekt.  Nicht jede Person die zu Meetings, Laboren oder Vorlesungen einlädt ist "Mitarbeiter".
