### ISSUE TITLE
Manuellen Checkin gegen automatisierte Fake-Logins absichern

### ISSUE THREAD

**Issue by oliverhummel** [informatik-mannheim/HSMA-CTT#85]
Morittz: Gegen die Fake-Einträge hatte ich noch die Idee einen z.B. 4 stelligen Pin auf die Printouts für jeden Raum zu schreiben, den man beim Check-in eingeben muss. Im QR wäre der natürlich integriert. Das verhindert zwar nicht alle Attacken, aber ich glaube kaum das sich jemand in der HS die Mühe macht, alle Zettel abklappert und die PINs Online leakt.

Tasks:
- [x] PIN im backend #76
- [x] PIN auf printouts #81 
- [x] PIN input und Überprüfung #79
